logging:
  level:
    org.springframework.security: DEBUG
spring:
  h2:
    console.enabled: true
security:
  basic.enabled: false
#spring.datasource.url:jdbc:mysql://127.0.0.1/test
#spring.datasource.username:sa
#spring.datasource.password:
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect